sudo: required
services:
  - docker

before_install:
  - docker build -t angelgoez/docker-and-kubernetes -f Dockerfile.dev .

script:
  - docker run -e CI=true angelgoez/docker-and-kubernetes npm run test